// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BannersCarousel from "./islands/BannersCarousel.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_MenuDesktop from "./islands/Header/MenuDesktop.tsx";
import * as $Header_MenuMobile from "./islands/Header/MenuMobile.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $InstitucionalBanners from "./islands/InstitucionalBanners.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $NewsletterShopify from "./islands/NewsletterShopify.tsx";
import * as $OrdersTable from "./islands/OrdersTable.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PreCheckout from "./islands/PreCheckout.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $SearchTerm from "./islands/SearchTerm.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $SwiperShelf from "./islands/SwiperShelf.tsx";
import * as $WinnersSection from "./islands/WinnersSection.tsx";
import * as $WishlistButton from "./islands/WishlistButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BannersCarousel.tsx": $BannersCarousel,
    "./islands/Filters.tsx": $Filters,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/MenuDesktop.tsx": $Header_MenuDesktop,
    "./islands/Header/MenuMobile.tsx": $Header_MenuMobile,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/InstitucionalBanners.tsx": $InstitucionalBanners,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/NewsletterShopify.tsx": $NewsletterShopify,
    "./islands/OrdersTable.tsx": $OrdersTable,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PreCheckout.tsx": $PreCheckout,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/SearchTerm.tsx": $SearchTerm,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/SwiperShelf.tsx": $SwiperShelf,
    "./islands/WinnersSection.tsx": $WinnersSection,
    "./islands/WishlistButton.tsx": $WishlistButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
