// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/BannersCarousel.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$5 from "./sections/ContactUs.tsx";
import * as $$$$$$6 from "./sections/Content/Benefits.tsx";
import * as $$$$$$7 from "./sections/Content/Faq.tsx";
import * as $$$$$$8 from "./sections/Content/Logos.tsx";
import * as $$$$$$9 from "./sections/Content/RichText.tsx";
import * as $$$$$$10 from "./sections/Content/Table.tsx";
import * as $$$$$$11 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$12 from "./sections/FAQ/Banners.tsx";
import * as $$$$$$13 from "./sections/FAQ/Questions.tsx";
import * as $$$$$$14 from "./sections/Footer/Footer.tsx";
import * as $$$$$$15 from "./sections/Gallery.tsx";
import * as $$$$$$16 from "./sections/GridBanners.tsx";
import * as $$$$$$17 from "./sections/Header/Header.tsx";
import * as $$$$$$18 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$19 from "./sections/Images/Carousel.tsx";
import * as $$$$$$20 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$21 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$22 from "./sections/InfoCards.tsx";
import * as $$$$$$23 from "./sections/InstitucionalBanners.tsx";
import * as $$$$$$24 from "./sections/Layout/Container.tsx";
import * as $$$$$$25 from "./sections/Layout/Flex.tsx";
import * as $$$$$$26 from "./sections/Layout/Grid.tsx";
import * as $$$$$$27 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$28 from "./sections/Layout/PDPColumn.tsx";
import * as $$$$$$29 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$30 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$31 from "./sections/MainBanner.tsx";
import * as $$$$$$32 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$33 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$34 from "./sections/MyAccount/MyAccount.tsx";
import * as $$$$$$35 from "./sections/MyAccount/OrderDetatils.tsx";
import * as $$$$$$36 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$37 from "./sections/PageTitle.tsx";
import * as $$$$$$38 from "./sections/PreCheckout.tsx";
import * as $$$$$$39 from "./sections/PrivacyPolicy/Text.tsx";
import * as $$$$$$40 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$41 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$42 from "./sections/Product/NotFound.tsx";
import * as $$$$$$43 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$44 from "./sections/Product/ProductDescription.tsx";
import * as $$$$$$45 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$46 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$47 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$48 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$49 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$50 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$51 from "./sections/ProductHighlight.tsx";
import * as $$$$$$52 from "./sections/ProductMetaFields.tsx";
import * as $$$$$$53 from "./sections/ProductNameCode.tsx";
import * as $$$$$$54 from "./sections/PromoCardPDP.tsx";
import * as $$$$$$55 from "./sections/PromotionInfosPDP.tsx";
import * as $$$$$$56 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$57 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$58 from "./sections/Steps.tsx";
import * as $$$$$$59 from "./sections/Theme/Theme.tsx";
import * as $$$$$$60 from "./sections/WinnersSection.tsx";
import * as $$$$$$$$$0 from "./actions/product/getVariants.ts";
import * as $$$$$$$$$1 from "./actions/user/createShopify.ts";
import * as $$$$$$$$$2 from "./actions/user/loginShopify.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/otima-sorte/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/otima-sorte/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/otima-sorte/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/otima-sorte/sections/BannersCarousel.tsx": $$$$$$1,
    "deco-sites/otima-sorte/sections/Category/CategoryBanner.tsx": $$$$$$2,
    "deco-sites/otima-sorte/sections/Category/CategoryGrid.tsx": $$$$$$3,
    "deco-sites/otima-sorte/sections/Category/CategoryList.tsx": $$$$$$4,
    "deco-sites/otima-sorte/sections/ContactUs.tsx": $$$$$$5,
    "deco-sites/otima-sorte/sections/Content/Benefits.tsx": $$$$$$6,
    "deco-sites/otima-sorte/sections/Content/Faq.tsx": $$$$$$7,
    "deco-sites/otima-sorte/sections/Content/Logos.tsx": $$$$$$8,
    "deco-sites/otima-sorte/sections/Content/RichText.tsx": $$$$$$9,
    "deco-sites/otima-sorte/sections/Content/Table.tsx": $$$$$$10,
    "deco-sites/otima-sorte/sections/Content/Testimonials.tsx": $$$$$$11,
    "deco-sites/otima-sorte/sections/FAQ/Banners.tsx": $$$$$$12,
    "deco-sites/otima-sorte/sections/FAQ/Questions.tsx": $$$$$$13,
    "deco-sites/otima-sorte/sections/Footer/Footer.tsx": $$$$$$14,
    "deco-sites/otima-sorte/sections/Gallery.tsx": $$$$$$15,
    "deco-sites/otima-sorte/sections/GridBanners.tsx": $$$$$$16,
    "deco-sites/otima-sorte/sections/Header/Header.tsx": $$$$$$17,
    "deco-sites/otima-sorte/sections/Images/BannerGrid.tsx": $$$$$$18,
    "deco-sites/otima-sorte/sections/Images/Carousel.tsx": $$$$$$19,
    "deco-sites/otima-sorte/sections/Images/ImageGallery.tsx": $$$$$$20,
    "deco-sites/otima-sorte/sections/Images/ShoppableBanner.tsx": $$$$$$21,
    "deco-sites/otima-sorte/sections/InfoCards.tsx": $$$$$$22,
    "deco-sites/otima-sorte/sections/InstitucionalBanners.tsx": $$$$$$23,
    "deco-sites/otima-sorte/sections/Layout/Container.tsx": $$$$$$24,
    "deco-sites/otima-sorte/sections/Layout/Flex.tsx": $$$$$$25,
    "deco-sites/otima-sorte/sections/Layout/Grid.tsx": $$$$$$26,
    "deco-sites/otima-sorte/sections/Layout/GridItem.tsx": $$$$$$27,
    "deco-sites/otima-sorte/sections/Layout/PDPColumn.tsx": $$$$$$28,
    "deco-sites/otima-sorte/sections/Links/LinkTree.tsx": $$$$$$29,
    "deco-sites/otima-sorte/sections/Links/Shortcuts.tsx": $$$$$$30,
    "deco-sites/otima-sorte/sections/MainBanner.tsx": $$$$$$31,
    "deco-sites/otima-sorte/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$32,
    "deco-sites/otima-sorte/sections/Miscellaneous/CookieConsent.tsx": $$$$$$33,
    "deco-sites/otima-sorte/sections/MyAccount/MyAccount.tsx": $$$$$$34,
    "deco-sites/otima-sorte/sections/MyAccount/OrderDetatils.tsx": $$$$$$35,
    "deco-sites/otima-sorte/sections/Newsletter/Newsletter.tsx": $$$$$$36,
    "deco-sites/otima-sorte/sections/PageTitle.tsx": $$$$$$37,
    "deco-sites/otima-sorte/sections/PreCheckout.tsx": $$$$$$38,
    "deco-sites/otima-sorte/sections/PrivacyPolicy/Text.tsx": $$$$$$39,
    "deco-sites/otima-sorte/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$40,
    "deco-sites/otima-sorte/sections/Product/ImageGallerySlider.tsx": $$$$$$41,
    "deco-sites/otima-sorte/sections/Product/NotFound.tsx": $$$$$$42,
    "deco-sites/otima-sorte/sections/Product/NotFoundChallenge.tsx": $$$$$$43,
    "deco-sites/otima-sorte/sections/Product/ProductDescription.tsx": $$$$$$44,
    "deco-sites/otima-sorte/sections/Product/ProductInfo.tsx": $$$$$$45,
    "deco-sites/otima-sorte/sections/Product/ProductShelf.tsx": $$$$$$46,
    "deco-sites/otima-sorte/sections/Product/ProductShelfTabbed.tsx": $$$$$$47,
    "deco-sites/otima-sorte/sections/Product/SearchResult.tsx": $$$$$$48,
    "deco-sites/otima-sorte/sections/Product/ShelfWithImage.tsx": $$$$$$49,
    "deco-sites/otima-sorte/sections/Product/Wishlist.tsx": $$$$$$50,
    "deco-sites/otima-sorte/sections/ProductHighlight.tsx": $$$$$$51,
    "deco-sites/otima-sorte/sections/ProductMetaFields.tsx": $$$$$$52,
    "deco-sites/otima-sorte/sections/ProductNameCode.tsx": $$$$$$53,
    "deco-sites/otima-sorte/sections/PromoCardPDP.tsx": $$$$$$54,
    "deco-sites/otima-sorte/sections/PromotionInfosPDP.tsx": $$$$$$55,
    "deco-sites/otima-sorte/sections/Social/InstagramPosts.tsx": $$$$$$56,
    "deco-sites/otima-sorte/sections/Social/WhatsApp.tsx": $$$$$$57,
    "deco-sites/otima-sorte/sections/Steps.tsx": $$$$$$58,
    "deco-sites/otima-sorte/sections/Theme/Theme.tsx": $$$$$$59,
    "deco-sites/otima-sorte/sections/WinnersSection.tsx": $$$$$$60,
  },
  "actions": {
    "deco-sites/otima-sorte/actions/product/getVariants.ts": $$$$$$$$$0,
    "deco-sites/otima-sorte/actions/user/createShopify.ts": $$$$$$$$$1,
    "deco-sites/otima-sorte/actions/user/loginShopify.ts": $$$$$$$$$2,
  },
  "apps": {
    "deco-sites/otima-sorte/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/otima-sorte/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/otima-sorte",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
